import { useEffect, useMemo, useState } from 'react'
import type { ReactNode } from 'react'
import type { SessaoTeeds } from '../core/teeds/conta'
import {
  atualizarAcessoCliente, criarAcessoCliente, definirProdutoCliente, listarClientes, listarComissoes, listarContasDeriv, listarOperacoesRobos,
  listarPlanos, listarProdutos, listarProdutosClientes, salvarPlano, salvarProduto,
  type ClienteProdutoRegistro, type ClienteRegistro, type ComissaoDia, type ContaDerivRegistro, type OperacaoRoboRegistro, type PlanoRegistro, type ProdutoRegistro,
} from '../core/teeds/clientes'

type Aba = 'visao' | 'inteligencia' | 'clientes' | 'acessos' | 'planos' | 'produtos' | 'comissoes'
const slug = (s: string) => s.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')
const data = (iso?: string | null) => iso ? new Date(iso).toLocaleDateString('pt-BR') : 'Sem vencimento'
const dataInput = (iso?: string | null) => iso ? iso.slice(0, 10) : ''
const expirou = (c: ClienteRegistro) => !!c.acessoExpiraEm && Date.parse(c.acessoExpiraEm) < Date.now()
const status = (c: ClienteRegistro) => expirou(c) && c.statusAcesso === 'ativo' ? 'expirado' : c.statusAcesso
const moeda = (centavos: number | null) => centavos == null ? 'Grátis' : (centavos / 100).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' })

export function AdminPanel({ sessao, comissoes }: { sessao: SessaoTeeds; comissoes?: ReactNode }) {
  const [aba, setAba] = useState<Aba>('visao')
  const [clientes, setClientes] = useState<ClienteRegistro[]>([])
  const [planos, setPlanos] = useState<PlanoRegistro[]>([])
  const [produtos, setProdutos] = useState<ProdutoRegistro[]>([])
  const [liberacoes, setLiberacoes] = useState<ClienteProdutoRegistro[]>([])
  const [contas, setContas] = useState<ContaDerivRegistro[]>([])
  const [movimento, setMovimento] = useState<ComissaoDia[]>([])
  const [operacoesRobos, setOperacoesRobos] = useState<OperacaoRoboRegistro[]>([])
  const [busca, setBusca] = useState('')
  const [filtro, setFiltro] = useState('todos')
  const [carregando, setCarregando] = useState(true)
  const [erro, setErro] = useState<string | null>(null)
  const [sucesso, setSucesso] = useState<string | null>(null)
  const [cliente, setCliente] = useState<ClienteRegistro | null>(null)
  const [clienteForm, setClienteForm] = useState({ planoId: 'essencial', status: 'ativo', expira: '', observacoes: '' })
  const [extras, setExtras] = useState<Set<string>>(new Set())
  const [novo, setNovo] = useState({ nome: '', email: '', telefone: '', cpf: '', senha: '', planoId: 'essencial', expira: '' })
  const [planoForm, setPlanoForm] = useState<PlanoRegistro | null>(null)
  const [produtoForm, setProdutoForm] = useState<ProdutoRegistro | null>(null)
  const [salvando, setSalvando] = useState(false)

  const carregar = async () => {
    setCarregando(true); setErro(null)
    try {
      const [c, p, pr, l, co, m, obr] = await Promise.all([listarClientes(sessao), listarPlanos(sessao), listarProdutos(sessao), listarProdutosClientes(sessao), listarContasDeriv(sessao), listarComissoes(sessao, 90), listarOperacoesRobos(sessao, 90)])
      setClientes(c); setPlanos(p); setProdutos(pr); setLiberacoes(l); setContas(co); setMovimento(m); setOperacoesRobos(obr)
    } catch (e) { setErro((e as Error).message) } finally { setCarregando(false) }
  }
  useEffect(() => { void carregar() }, [sessao.usuario.id]) // eslint-disable-line react-hooks/exhaustive-deps

  const ativos = clientes.filter((c) => status(c) === 'ativo').length
  const expirados = clientes.filter((c) => status(c) === 'expirado').length
  const vencendo = clientes.filter((c) => c.acessoExpiraEm && !expirou(c) && Date.parse(c.acessoExpiraEm) - Date.now() <= 7 * 864e5).length
  const ativos24h = clientes.filter(c => Date.now() - Date.parse(c.vistoEm) <= 864e5).length
  const saldoReal = contas.filter(c => c.tipo !== 'demo').reduce((s,c)=>s+(c.saldo??0),0)
  const markup90 = movimento.filter(m=>!m.demo).reduce((s,m)=>s+m.comissao,0)
  const operacoes90 = movimento.reduce((s,m)=>s+m.operacoes,0)
  const clienteInfo = (id:string) => ({ contas: contas.filter(c=>c.userId===id), movimento: movimento.filter(m=>m.userId===id), extras: liberacoes.filter(x=>x.userId===id&&x.ativo) })
  const ranking = clientes.map(c=>({cliente:c, comissao:clienteInfo(c.userId).movimento.filter(m=>!m.demo).reduce((s,m)=>s+m.comissao,0), operacoes:clienteInfo(c.userId).movimento.reduce((s,m)=>s+m.operacoes,0)})).sort((a,b)=>b.comissao-a.comissao)
  const planosDist = planos.map(p=>({nome:p.nome,total:clientes.filter(c=>c.planoId===p.id).length})).filter(p=>p.total)
  const maxPlano = Math.max(1,...planosDist.map(p=>p.total))
  const porRobo = [...operacoesRobos.reduce((map,op)=>{ const atual=map.get(op.roboId)??{id:op.roboId,nome:op.roboNome,operacoes:0,markup:0,volume:0,resultado:0,vitorias:0,clientes:new Set<string>()}; atual.operacoes++; atual.markup+=op.demo?0:op.markup; atual.volume+=op.entrada; atual.resultado+=op.resultado; atual.vitorias+=op.ganhou?1:0; atual.clientes.add(op.userId); map.set(op.roboId,atual); return map },new Map<string,{id:string;nome:string;operacoes:number;markup:number;volume:number;resultado:number;vitorias:number;clientes:Set<string>}>()).values()].sort((a,b)=>b.markup-a.markup)
  const visiveis = useMemo(() => clientes.filter((c) => {
    const q = busca.trim().toLowerCase()
    return (!q || `${c.nome} ${c.email} ${c.telefone} ${c.cpf}`.toLowerCase().includes(q)) && (filtro === 'todos' || status(c) === filtro)
  }), [clientes, busca, filtro])

  const abrirCliente = (c: ClienteRegistro) => {
    setCliente(c); setClienteForm({ planoId: c.planoId, status: status(c), expira: dataInput(c.acessoExpiraEm), observacoes: c.observacoes ?? '' })
    setExtras(new Set(liberacoes.filter((x) => x.userId === c.userId && x.ativo).map((x) => x.produtoId)))
  }
  const salvarCliente = async () => {
    if (!cliente) return
    setSalvando(true); setErro(null)
    try {
      await atualizarAcessoCliente(sessao, cliente.userId, { planoId: clienteForm.planoId, statusAcesso: clienteForm.status as ClienteRegistro['statusAcesso'], acessoExpiraEm: clienteForm.expira ? new Date(`${clienteForm.expira}T23:59:59`).toISOString() : null, observacoes: clienteForm.observacoes || null })
      await Promise.all(produtos.map((p) => definirProdutoCliente(sessao, cliente.userId, p.id, extras.has(p.id))))
      setCliente(null); setSucesso('Acesso atualizado com sucesso.'); await carregar()
    } catch (e) { setErro((e as Error).message) } finally { setSalvando(false) }
  }
  const criar = async () => {
    if (!novo.nome.trim() || !novo.email.trim() || novo.senha.length < 6) { setErro('Preencha nome, e-mail e uma senha provisória com pelo menos 6 caracteres.'); return }
    setSalvando(true); setErro(null); setSucesso(null)
    try {
      const r = await criarAcessoCliente(sessao, novo)
      if (r.userId) await atualizarAcessoCliente(sessao, r.userId, { planoId: novo.planoId, statusAcesso: 'ativo', acessoExpiraEm: novo.expira ? new Date(`${novo.expira}T23:59:59`).toISOString() : null, observacoes: null })
      setNovo({ nome: '', email: '', telefone: '', cpf: '', senha: '', planoId: 'essencial', expira: '' })
      setSucesso(r.precisaConfirmar ? 'Acesso criado. O cliente precisa confirmar o e-mail antes de entrar.' : 'Acesso criado e liberado com sucesso.')
      await carregar(); setAba('clientes')
    } catch (e) { setErro((e as Error).message) } finally { setSalvando(false) }
  }
  const gravarPlano = async () => { if (!planoForm?.nome.trim()) return; setSalvando(true); try { await salvarPlano(sessao, { ...planoForm, id: planoForm.id || slug(planoForm.nome) }); setPlanoForm(null); setSucesso('Plano salvo.'); await carregar() } catch(e){setErro((e as Error).message)} finally{setSalvando(false)} }
  const gravarProduto = async () => { if (!produtoForm?.nome.trim()) return; setSalvando(true); try { await salvarProduto(sessao, { ...produtoForm, id: produtoForm.id || slug(produtoForm.nome) }); setProdutoForm(null); setSucesso('Produto salvo.'); await carregar() } catch(e){setErro((e as Error).message)} finally{setSalvando(false)} }

  const tabelaClientes = <><div className="adm-filtros"><label>⌕<input placeholder="Buscar nome, e-mail, telefone ou CPF" value={busca} onChange={(e) => setBusca(e.target.value)} /></label><select value={filtro} onChange={(e) => setFiltro(e.target.value)}><option value="todos">Todos os status</option><option value="ativo">Ativos</option><option value="suspenso">Suspensos</option><option value="expirado">Expirados</option><option value="cancelado">Cancelados</option></select></div><div className="adm-tabela"><div className="adm-linha cab"><span>Cliente</span><span>Plano</span><span>Status</span><span>Último acesso</span><span>Saldo Deriv</span><span>Cadastro</span><span /></div>{visiveis.map((c) => { const info=clienteInfo(c.userId); const saldo=info.contas.reduce((s,x)=>s+(x.saldo??0),0); const st = status(c); return <button className="adm-linha" key={c.userId} onClick={() => abrirCliente(c)}><span className="adm-pessoa"><i>{(c.nome || c.email || '?')[0].toUpperCase()}</i><b>{c.nome || 'Sem nome'}<small>{c.email}</small></b></span><span>{planos.find((p) => p.id === c.planoId)?.nome ?? c.planoId}</span><span><em className={`adm-status ${st}`}>{st}</em></span><span>{data(c.vistoEm)}</span><span>{info.contas.length?`US$ ${saldo.toLocaleString('pt-BR',{minimumFractionDigits:2})}`:'Não conectada'}</span><span>{data(c.criadoEm)}</span><span className="adm-seta">›</span></button>})}{!carregando && !visiveis.length && <div className="adm-vazio">Nenhum cliente encontrado.</div>}</div></>

  return <div className="admin-shell">
    <aside className="admin-sidebar"><div><span className="rot">Painel de controle</span><h2>Administração</h2><p>Gestão completa da Teeds</p></div><nav>{([['visao','Visão geral','⌂'],['inteligencia','Inteligência','◫'],['clientes','Clientes','◎'],['acessos','Criar acesso','＋'],['planos','Planos','▣'],['produtos','Produtos','◇'],['comissoes','Comissões','↗']] as [Aba,string,string][]).map(([id,nome,ico]) => <button key={id} className={aba === id ? 'on' : ''} onClick={() => setAba(id)}><i>{ico}</i><span>{nome}</span>{id === 'clientes' && <b>{clientes.length}</b>}</button>)}</nav><small>Somente administradores podem visualizar e alterar estes dados.</small></aside>
    <main className="admin-main"><header className="admin-top"><div><span className="rot">Teeds Admin</span><h1>{aba === 'visao' ? 'Visão geral' : aba === 'inteligencia' ? 'Inteligência do negócio' : aba === 'clientes' ? 'Gestão de clientes' : aba === 'acessos' ? 'Criar novo acesso' : aba === 'planos' ? 'Planos e assinaturas' : aba === 'produtos' ? 'Catálogo de produtos' : 'Comissões e resultados'}</h1><p>{aba === 'visao' ? 'Tudo que precisa de atenção, em um só lugar.' : aba === 'inteligencia' ? 'Comportamento, carteira, atividade e receita organizados para decidir melhor.' : aba === 'clientes' ? 'Consulte, filtre e edite acessos existentes.' : aba === 'acessos' ? 'Cadastre uma pessoa e defina sua liberação inicial.' : aba === 'planos' ? 'Configure as opções comerciais da plataforma.' : aba === 'produtos' ? 'Gerencie os itens e extras do Marketplace.' : 'Acompanhe volume, operações e comissões da sua conta.'}</p></div><button className="admin-refresh" onClick={() => void carregar()} disabled={carregando}>↻ {carregando ? 'Atualizando…' : 'Atualizar'}</button></header>
      {erro && <div className="ger-erro">{erro}<button onClick={() => setErro(null)}>×</button></div>}{sucesso && <div className="admin-sucesso">✓ {sucesso}<button onClick={() => setSucesso(null)}>×</button></div>}
      {aba === 'visao' && <><div className="adm-kpis admin-kpis-click"><button onClick={()=>setAba('clientes')}><span>Clientes cadastrados</span><strong>{clientes.length}</strong><small>ver base completa →</small></button><button className="ok" onClick={()=>setAba('inteligencia')}><span>Ativos nas últimas 24h</span><strong>{ativos24h}</strong><small>{ativos} acessos liberados</small></button><button className="alerta" onClick={()=>setAba('comissoes')}><span>Markup real · 90 dias</span><strong>US$ {markup90.toFixed(2)}</strong><small>{operacoes90.toLocaleString('pt-BR')} operações</small></button><button className="perigo" onClick={()=>{setFiltro('expirado');setAba('clientes')}}><span>Expirados</span><strong>{expirados}</strong><small>{vencendo} vencem em 7 dias</small></button></div><div className="admin-grid"><section className="admin-card"><header><div><span className="rot">Clientes recentes</span><h3>Últimos cadastros</h3></div><button onClick={() => setAba('clientes')}>Ver todos →</button></header>{clientes.slice(0,5).map(c=><button className="admin-mini" key={c.userId} onClick={()=>abrirCliente(c)}><span className="adm-pessoa"><i>{(c.nome||c.email||'?')[0].toUpperCase()}</i><b>{c.nome||'Sem nome'}<small>{c.email}</small></b></span><span className="admin-last">Último acesso<b>{data(c.vistoEm)}</b></span><em className={`adm-status ${status(c)}`}>{status(c)}</em></button>)}</section><section className="admin-card"><header><div><span className="rot">Atalhos</span><h3>Ações rápidas</h3></div></header><button className="admin-quick primary" onClick={()=>setAba('acessos')}><i>＋</i><span><b>Criar novo acesso</b><small>Cadastrar e liberar um cliente</small></span></button><button className="admin-quick" onClick={()=>setAba('inteligencia')}><i>◫</i><span><b>Analisar a base</b><small>Atividade, carteira e distribuição</small></span></button><button className="admin-quick" onClick={()=>setAba('comissoes')}><i>↗</i><span><b>Ver comissões</b><small>Markup, volume e evolução</small></span></button></section></div></>}
      {aba === 'inteligencia' && <><div className="adm-kpis"><article><span>Saldo real conectado</span><strong>US$ {saldoReal.toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2})}</strong><small>{contas.filter(c=>c.tipo!=='demo').length} contas reais</small></article><article className="ok"><span>Taxa de atividade · 24h</span><strong>{clientes.length?Math.round(ativos24h/clientes.length*100):0}%</strong><small>{ativos24h} de {clientes.length} clientes</small></article><article className="alerta"><span>Operações · 90 dias</span><strong>{operacoes90.toLocaleString('pt-BR')}</strong><small>reais e demonstração</small></article><article><span>Produtos liberados</span><strong>{liberacoes.filter(x=>x.ativo).length}</strong><small>em todas as contas</small></article></div><div className="admin-analytics"><section className="admin-card"><header><div><span className="rot">Distribuição</span><h3>Clientes por plano</h3></div></header><div className="admin-bars">{planosDist.map(p=><div key={p.nome}><span>{p.nome}<b>{p.total}</b></span><i><em style={{width:`${p.total/maxPlano*100}%`}}/></i></div>)}</div></section><section className="admin-card"><header><div><span className="rot">Ranking real · 90 dias</span><h3>Markup por cliente</h3></div></header><div className="admin-ranking">{ranking.slice(0,7).map((r,i)=><button key={r.cliente.userId} onClick={()=>abrirCliente(r.cliente)}><i>{i+1}</i><span><b>{r.cliente.nome||r.cliente.email}</b><small>{r.operacoes.toLocaleString('pt-BR')} operações</small></span><strong>US$ {r.comissao.toFixed(2)}</strong></button>)}</div></section></div><section className="admin-card admin-data-note"><header><div><span className="rot">Qualidade dos dados</span><h3>Rastreabilidade e próximos dados</h3></div></header><div className="admin-data-grid"><div className="ok"><i>✓</i><span><b>Disponível agora</b><small>Cadastro, último acesso, plano, validade, produtos, contas Deriv, saldo, operações e markup por cliente.</small></span></div><div><i>→</i><span><b>Localização</b><small>Não é coletada atualmente. Deve exigir consentimento e política de privacidade antes da ativação.</small></span></div><div><i>→</i><span><b>Markup por robô</b><small>A origem do robô ainda não é enviada ao banco. O painel não mistura estimativa com dinheiro real.</small></span></div></div></section></>}
      {aba === 'inteligencia' && <section className="admin-card admin-robot-metrics"><header><div><span className="rot">Telemetria real · 90 dias</span><h3>Desempenho e markup por robô</h3></div><small>Dados coletados a partir desta implantação</small></header>{porRobo.length?<div className="admin-robo-table"><div className="cab"><span>Robô</span><span>Operações</span><span>Acerto</span><span>Clientes</span><span>Volume</span><span>Resultado</span><span>Markup real</span></div>{porRobo.map(r=><div key={r.id}><span><b>{r.nome}</b><small>{r.id}</small></span><span>{r.operacoes.toLocaleString('pt-BR')}</span><span>{r.operacoes?(r.vitorias/r.operacoes*100).toFixed(1):'0'}%</span><span>{r.clientes.size}</span><span>US$ {r.volume.toFixed(2)}</span><span className={r.resultado>=0?'positivo':'negativo'}>{r.resultado>=0?'+':''}{r.resultado.toFixed(2)}</span><strong>US$ {r.markup.toFixed(2)}</strong></div>)}</div>:<div className="adm-vazio">A coleta por robô está pronta. Os indicadores serão preenchidos conforme novos contratos forem concluídos.</div>}</section>}
      {aba === 'clientes' && <section className="admin-card full"><header><div><span className="rot">Base completa</span><h3>{clientes.length} clientes cadastrados</h3></div><button className="admin-primary" onClick={()=>setAba('acessos')}>＋ Novo cliente</button></header>{tabelaClientes}</section>}
      {aba === 'acessos' && <section className="admin-form-page"><div className="admin-form-intro"><span>01</span><h3>Dados do cliente</h3><p>O e-mail será usado para entrar na plataforma.</p></div><div className="admin-form-grid"><label><span>Nome completo *</span><input value={novo.nome} onChange={e=>setNovo({...novo,nome:e.target.value})} placeholder="Nome e sobrenome" /></label><label><span>E-mail de acesso *</span><input type="email" value={novo.email} onChange={e=>setNovo({...novo,email:e.target.value})} placeholder="cliente@email.com" /></label><label><span>Telefone</span><input value={novo.telefone} onChange={e=>setNovo({...novo,telefone:e.target.value})} placeholder="(00) 00000-0000" /></label><label><span>CPF</span><input value={novo.cpf} onChange={e=>setNovo({...novo,cpf:e.target.value})} placeholder="000.000.000-00" /></label><label><span>Senha provisória *</span><input type="password" value={novo.senha} onChange={e=>setNovo({...novo,senha:e.target.value})} placeholder="Mínimo de 6 caracteres" /></label><label><span>Plano inicial</span><select value={novo.planoId} onChange={e=>setNovo({...novo,planoId:e.target.value})}>{planos.filter(p=>p.ativo).map(p=><option key={p.id} value={p.id}>{p.nome}</option>)}</select></label><label><span>Validade do acesso</span><input type="date" value={novo.expira} onChange={e=>setNovo({...novo,expira:e.target.value})} /></label></div><footer><p>O cliente poderá alterar a senha depois pelo fluxo “Esqueci minha senha”.</p><button className="admin-primary" onClick={()=>void criar()} disabled={salvando}>{salvando?'Criando…':'Criar e liberar acesso'}</button></footer></section>}
      {aba === 'planos' && <section className="admin-catalogo"><header><button className="admin-primary" onClick={()=>setPlanoForm({id:'',nome:'',duracaoDias:30,ativo:true})}>＋ Criar plano</button></header><div>{planos.map(p=><article key={p.id}><span className="admin-icon">▣</span><div><h3>{p.nome}</h3><p>{p.duracaoDias ? `${p.duracaoDias} dias de acesso` : 'Acesso sem vencimento'}</p></div><em className={`adm-status ${p.ativo?'ativo':'cancelado'}`}>{p.ativo?'Ativo':'Inativo'}</em><button onClick={()=>setPlanoForm(p)}>Editar</button></article>)}</div></section>}
      {aba === 'produtos' && <section className="admin-catalogo"><header><button className="admin-primary" onClick={()=>setProdutoForm({id:'',nome:'',categoria:'robo',precoCentavos:19700,ativo:true})}>＋ Criar produto</button></header><div>{produtos.map(p=><article key={p.id}><span className="admin-icon">◇</span><div><h3>{p.nome}</h3><p>{p.categoria} · {moeda(p.precoCentavos)}</p></div><em className={`adm-status ${p.ativo?'ativo':'cancelado'}`}>{p.ativo?'Ativo':'Inativo'}</em><button onClick={()=>setProdutoForm(p)}>Editar</button></article>)}</div></section>}
      {aba === 'comissoes' && <section className="admin-commission">{comissoes}</section>}
    </main>
    {cliente && <div className="adm-modal-fundo" onMouseDown={()=>setCliente(null)}><section className="adm-modal" onMouseDown={e=>e.stopPropagation()}><header><div className="adm-pessoa"><i>{(cliente.nome||cliente.email||'?')[0].toUpperCase()}</i><b>{cliente.nome||'Sem nome'}<small>{cliente.email}</small></b></div><button onClick={()=>setCliente(null)}>×</button></header><div className="adm-detail-kpis"><div><span>Último acesso</span><b>{data(cliente.vistoEm)}</b></div><div><span>Desde o cadastro</span><b>{Math.max(0,Math.floor((Date.now()-Date.parse(cliente.criadoEm))/864e5))} dias</b></div><div><span>Operações · 90d</span><b>{clienteInfo(cliente.userId).movimento.reduce((s,m)=>s+m.operacoes,0).toLocaleString('pt-BR')}</b></div><div><span>Markup real · 90d</span><b>US$ {clienteInfo(cliente.userId).movimento.filter(m=>!m.demo).reduce((s,m)=>s+m.comissao,0).toFixed(2)}</b></div></div><div className="adm-contas"><span className="rot">Contas conectadas na corretora</span>{clienteInfo(cliente.userId).contas.length?clienteInfo(cliente.userId).contas.map(c=><div key={c.contaId}><span><b>{c.contaId}</b><small>{c.tipo==='demo'?'Demonstração':'Conta real'} · vista em {data(c.vistaEm)}</small></span><strong>{c.moeda||'USD'} {(c.saldo??0).toLocaleString('pt-BR',{minimumFractionDigits:2})}</strong></div>):<p>Nenhuma conta Deriv conectada.</p>}</div><div className="adm-form"><label><span>Plano</span><select value={clienteForm.planoId} onChange={e=>setClienteForm({...clienteForm,planoId:e.target.value})}>{planos.map(p=><option key={p.id} value={p.id}>{p.nome}</option>)}</select></label><label><span>Status</span><select value={clienteForm.status} onChange={e=>setClienteForm({...clienteForm,status:e.target.value})}><option value="ativo">Ativo</option><option value="suspenso">Suspenso</option><option value="expirado">Expirado</option><option value="cancelado">Cancelado</option></select></label><label><span>Expira em</span><input type="date" value={clienteForm.expira} onChange={e=>setClienteForm({...clienteForm,expira:e.target.value})}/></label></div><div className="adm-extras"><span className="rot">Produtos e extras liberados</span>{produtos.map(p=><label key={p.id}><input type="checkbox" checked={extras.has(p.id)} onChange={()=>setExtras(x=>{const n=new Set(x);n.has(p.id)?n.delete(p.id):n.add(p.id);return n})}/><span><b>{p.nome}</b><small>{p.categoria}</small></span></label>)}</div><label className="adm-notas"><span>Observações internas</span><textarea value={clienteForm.observacoes} onChange={e=>setClienteForm({...clienteForm,observacoes:e.target.value})}/></label><footer><button className="adm-cancelar" onClick={()=>setClienteForm({...clienteForm,status:'cancelado'})}>Encerrar acesso</button><span>Cadastrado em {data(cliente.criadoEm)}</span><button onClick={()=>void salvarCliente()} disabled={salvando}>{salvando?'Salvando…':'Salvar alterações'}</button></footer></section></div>}
    {planoForm && <Editor titulo={planoForm.id?'Editar plano':'Novo plano'} fechar={()=>setPlanoForm(null)} salvar={gravarPlano} salvando={salvando}><label><span>Nome</span><input value={planoForm.nome} onChange={e=>setPlanoForm({...planoForm,nome:e.target.value})}/></label><label><span>Duração em dias</span><input type="number" min="1" placeholder="Vazio = sem vencimento" value={planoForm.duracaoDias??''} onChange={e=>setPlanoForm({...planoForm,duracaoDias:e.target.value?Number(e.target.value):null})}/></label><label className="admin-check"><input type="checkbox" checked={planoForm.ativo} onChange={e=>setPlanoForm({...planoForm,ativo:e.target.checked})}/> Plano disponível</label></Editor>}
    {produtoForm && <Editor titulo={produtoForm.id?'Editar produto':'Novo produto'} fechar={()=>setProdutoForm(null)} salvar={gravarProduto} salvando={salvando}><label><span>Nome</span><input value={produtoForm.nome} onChange={e=>setProdutoForm({...produtoForm,nome:e.target.value})}/></label><label><span>Categoria</span><select value={produtoForm.categoria} onChange={e=>setProdutoForm({...produtoForm,categoria:e.target.value})}><option value="robo">Robô</option><option value="mentoria">Mentoria</option><option value="ferramenta">Ferramenta</option><option value="indicador">Indicador</option><option value="sala">Sala de sinais</option></select></label><label><span>Preço (R$)</span><input type="number" min="0" step="0.01" value={(produtoForm.precoCentavos??0)/100} onChange={e=>setProdutoForm({...produtoForm,precoCentavos:Math.round(Number(e.target.value)*100)})}/></label><label className="admin-check"><input type="checkbox" checked={produtoForm.ativo} onChange={e=>setProdutoForm({...produtoForm,ativo:e.target.checked})}/> Produto disponível</label></Editor>}
  </div>
}

function Editor({titulo,fechar,salvar,salvando,children}:{titulo:string;fechar:()=>void;salvar:()=>void;salvando:boolean;children:ReactNode}) { return <div className="adm-modal-fundo" onMouseDown={fechar}><section className="adm-modal admin-editor" onMouseDown={e=>e.stopPropagation()}><header><h3>{titulo}</h3><button onClick={fechar}>×</button></header><div className="admin-editor-form">{children}</div><footer><span>As alterações entram em vigor imediatamente.</span><button onClick={salvar} disabled={salvando}>{salvando?'Salvando…':'Salvar'}</button></footer></section></div> }
